# Generated by Django 2.2 on 2020-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('1', 'Point fixe 1'), ('2', 'Point fixe - Loueur de bateau'), ('3', 'Livraison sur bateau')], max_length=100),
        ),
    ]
