# Generated by Django 2.2 on 2020-02-17 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200216_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_de_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
