# Generated by Django 2.2 on 2020-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_of_order',
            field=models.CharField(choices=[('Dejeuner', 'Dejeuner'), ('Apero', 'Apero')], default='Dejeuner', max_length=50),
        ),
    ]
