# Generated by Django 2.2 on 2020-02-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_type_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.CharField(choices=[('Apero', 'Apero'), ('Dejeuner', 'Dejeuner')], default='Dejeuner', max_length=30),
        ),
    ]
