# Generated by Django 2.2 on 2019-11-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
