# Generated by Django 2.2 on 2020-03-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200226_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='numero_delivery',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='rang_delivery',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='info',
            name='zone_delivery',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('1', 'Point fixe 1'), ('2', 'Point fixe - Loueur de bateau'), ('3', 'Livraison-sur-bateau')], max_length=100),
        ),
    ]
