# Generated by Django 2.2 on 2020-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200303_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='numero_delivery',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='rang_delivery',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='zone_delivery',
            field=models.CharField(max_length=30),
        ),
    ]
