# Generated by Django 2.2 on 2020-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200309_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_de_creation',)},
        ),
        migrations.AddField(
            model_name='info',
            name='creneau_delivery',
            field=models.CharField(default='10', max_length=30),
        ),
    ]
