# Generated by Django 2.2 on 2020-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200323_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couvert',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
