# Generated by Django 2.2 on 2020-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_couvert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='creneau_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='creneau_delivery',
            field=models.CharField(default='10', max_length=30),
        ),
    ]
