# Generated by Django 2.2 on 2020-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200410_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creneau_delivery',
            field=models.CharField(blank=True, default='10', max_length=30, null=True),
        ),
    ]
