# Generated by Django 2.2 on 2020-04-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200411_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Recommandation utilisateur', 'verbose_name_plural': 'Recommadation utilisateur'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Informations utilisateurs', 'verbose_name_plural': 'Informations utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_de_creation',), 'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Commande - Produit', 'verbose_name_plural': 'Commande - Produits'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Demande de remboursement', 'verbose_name_plural': 'Demandes de remboursement'},
        ),
    ]
