# Generated by Django 2.2 on 2020-04-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200414_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cgv',
        ),
    ]
