# Generated by Django 2.2 on 2019-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191128_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entrées', 'Entrées'), ('Boissons', 'Boissons'), ('Plats', 'Plats'), ('Desserts', 'Desserts')], default='Plats', max_length=32),
        ),
    ]
