# Generated by Django 2.2 on 2020-04-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_order_cgv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantite',
        ),
    ]
