# Generated by Django 2.2 on 2019-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default='2000-12-12'),
            preserve_default=False,
        ),
    ]
