# Generated by Django 2.2 on 2020-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_product_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='zone_delivery',
            field=models.CharField(default='', max_length=30),
        ),
    ]
