# Generated by Django 2.2 on 2019-12-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
    ]
