# Generated by Django 2.2 on 2019-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entrées', 'Entrées'), ('Boissons', 'Boissons'), ('Plats', 'Plats'), ('Desserts', 'Desserts'), ('Accessoires', 'Accessoires')], default='Plats', max_length=32),
        ),
    ]
