# Generated by Django 2.2 on 2020-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200420_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
