# Generated by Django 2.2 on 2020-04-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
