# Generated by Django 2.2 on 2020-02-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191212_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
