# Generated by Django 2.2 on 2020-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order_date_de_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_de_livraison',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
