# Generated by Django 2.2 on 2020-04-24 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200424_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_de_livraison',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
