# Generated by Django 2.2 on 2020-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200428_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entrées', 'Entrées & Tapas'), ('Salades', 'Salades, Taboulés & Quiche'), ('Fromage', 'Fromages & Charcuterie'), ('Desserts', 'Desserts'), ('Enfant', 'Panier enfant'), ('Boissons', 'Boissons & Café'), ('Plats', 'Plats'), ('Accessoires', 'Accessoires')], default='Plats', max_length=32),
        ),
    ]
