# Generated by Django 2.2 on 2020-05-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200501_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='email',
        ),
    ]
