# Generated by Django 2.2 on 2020-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_avis_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loueur_de_bateau',
            field=models.CharField(blank=True, choices=[('', 'Choisissez'), ('bat-express', 'Bat Express'), ('ferret-marine', 'Ferret Marine'), ('sensey', 'Sensey')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('ecole-de-voile', 'Ecole de voile'), ('loueur-bateau', 'Loueur bateau'), ('bateau-fixe', 'Bateau fixe'), ('livraison-sur-bateau', 'Livraison sur bateau')], max_length=100),
        ),
    ]
