# Generated by Django 2.2 on 2020-05-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200501_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='loueur_de_bateau',
            new_name='loueur_bateau',
        ),
    ]
