# Generated by Django 2.2 on 2020-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='category',
            field=models.CharField(choices=[('boisson', 'Boisson'), ('sandwich', 'Sandwich'), ('dessert', 'Dessert'), ('huitre', 'Huitre')], default='Boisson', max_length=100),
        ),
    ]
