# Generated by Django 2.2 on 2020-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200502_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('boisson', 'boisson'), ('sandwich', 'sandwich'), ('dessert', 'dessert'), ('huitre', 'huitre')], default='boisson', max_length=100),
        ),
    ]
