# Generated by Django 2.2 on 2020-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200504_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='dessert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
