# Generated by Django 2.2 on 2020-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200504_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcool',
            field=models.BooleanField(default=False),
        ),
    ]
