# Generated by Django 2.2 on 2020-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_avis_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('boisson', 'boisson'), ('sandwich', 'sandwich'), ('dessert', 'dessert'), ('huitre', 'huitre'), ('alcool', 'alcool')], default='boisson', max_length=100),
        ),
    ]
