# Generated by Django 2.2 on 2020-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20200519_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='creneau_delivery',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
