# Generated by Django 2.2 on 2020-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200522_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='huitre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
