# Generated by Django 2.2 on 2020-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_orderproduct_huitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ManyToManyField(related_name='variation', to='main.Product'),
        ),
    ]
