# Generated by Django 2.2 on 2020-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200529_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
